services:
  pos_mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: defaultdb
      MYSQL_USER: pos_user
      MYSQL_PASSWORD: pos_pw
    ports:
      - "3306:3306"
  pos_service:
    image: playofferservice
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"