services:
  pos_redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"
  pos_mysql:
    image: mysql:8
    command: 
      - --default-authentication-plugin=mysql_native_password
      - mysql -uroot -prootpw -e "SET @@GLOBAL.ENFORCE_GTID_CONSISTENCY = ON;SET @@GLOBAL.GTID_MODE = OFF_PERMISSIVE;SET @@GLOBAL.GTID_MODE = ON_PERMISSIVE;SET @@GLOBAL.GTID_MODE = ON;"
      - 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: defaultdb
      MYSQL_USER: pos_user
      MYSQL_PASSWORD: pos_pw
    ports:
      - "3306:3306"
  pos_service:
    image: playofferservice
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"