apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-debezium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pos-debezium
  template:
    metadata:
      labels:
        app: pos-debezium
    spec:
      containers:
        - name: pos-debezium
          image: debezium/server
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: debezium-conf
              mountPath: /debezium/conf
      volumes:
        - name: debezium-conf
          hostPath:
            path: C:\Users\bmaye\Desktop\Projects\School\PlayOfferService\debezium-conf
---
apiVersion: v1
kind: Service
metadata:
  name: pos-debezium
spec:
  selector:
    app: pos-debezium
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
