namespace PlayOfferService.Domain.Events;

public enum EventType
{
    PLAYOFFER_CREATED,
    PLAYOFFER_JOINED,
    PLAYOFFER_CANCELLED,
    PLAYOFFER_RESERVATION_CREATED,
    TENNIS_CLUB_REGISTERED,
    TENNIS_CLUB_LOCKED,
    TENNIS_CLUB_UNLOCKED
}