namespace PlayOfferService.Domain.Events;

public enum EventType
{
    PLAYOFFER_CREATED,
    PLAYOFFER_JOINED,
    PLAYOFFER_CANCELLED,
    ReservationCreatedEvent,
    TENNIS_CLUB_REGISTERED,
    TENNIS_CLUB_LOCKED,
    TENNIS_CLUB_UNLOCKED,
    TENNIS_CLUB_DELETED,
    MEMBER_REGISTERED,
    MEMBER_LOCKED,
    MEMBER_UNLOCKED,
    MEMBER_DELETED,
}